class AdvTagList {
  advTagFloat = 'IndexFloat';///悬浮弹窗
  advBaiKeFloat = 'baikeFloat';///悬浮弹窗
  advTagDialog = 'IndexPop';///弹窗
  advTagHomeBanner = 'IndexBanner';/// 首页Banner
  advTagCourseBanner  = 'CourseBanner';///课程页面banner
  advTagNewsDetailBanner = 'NewsDetailBanner';///动态详情页banner
  advTagNewsIndexBanner = 'NewsIndexBanner';///  动态页banner
  advTagQuestionsBanner = 'QuestionsBanner';///搜题页面banner
  advTagBrushTopicBanner = 'BrushTopicBanner';///刷题(学习)页面banner
  advTagRecruitBanner = 'RecruitBanner';///招考页面banner
  advTagCollegeBanner = 'CollegeBanner';///志愿页面banner
  advTagIndexMiniBanner = 'IndexMiniBanner';///首页功能区Banner
  advTagMyTxtBanner = 'personalMidText';///我的页面上面畅学卡部分文字广告
  advTagMyToolsBanner = 'QuestionBanner';///我的页面底部实用工具Banner
  advTagIndexMidaBanner = 'IndexMidaBanner';///成考首页banner下广告
  guideConcentrationTagNewsIndexBanner = 'DYSelectedCentralBanner';///  导游资格证精选页banner
  advTagStudyPlanBanner = 'studyPlanBanner';///备考方案广告配置
  advTagFiveStarBanner = 'fiveStarPraise';///我的页面五星好评领券广告
  advTagStudyPlanPop = 'studyPlanPop';///备考方案弹窗广告配置
  advTagambitionMiniBanner = 'ambitionMiniBanner';///高职单招志愿板块顶部广告配置
  advTagNewerGiftBottomBanner = 'newerGiftBottomBanner';///新人专享跟多福利底部广告
  advTagCoursePreSales = 'coursePreSales';//课程详情页：coursePreSales
  advTagCoursePreSalesText = 'coursePreSalesText';//课程购买确认订单页 coursePreSalesText
  advTagCourseAfterSalesText = 'courseAfterSalesText';//课程购买成功售后联系客服 courseAfterSalesText
  advTagCourseAfterSalesBtn = 'courseAfterSalesBtn';//课程支付成功页领取讲义 courseAfterSalesBtn
  advTagSetmealPreSales = 'setmealPreSales';//套餐详情页：setmealPreSales
  advTagSetmealPreSalesText = 'setmealPreSalesText';//套餐购买确认订单页 setmealPreSalesText
  advTagSetmealAfterSalesText = 'setmealAfterSalesText';//套餐购买成功售后联系客服 setmealAfterSalesText
  advTagSetmealAfterSalesBtn = 'setmealAfterSalesBtn';//套餐支付成功页领取讲义 setmealAfterSalesBtn
  advTagQuestionPreSalesText = 'questionPreSalesText';//畅学卡购买页-售前联系客服 questionPreSalesText
  advTagQuestionAfterSalesText = 'questionAfterSalesText';//畅学卡支付成功页-售后联系客服 questionAfterSalesText
  advTagQuestionAfterSalesBtn = 'questionAfterSalesBtn';//畅学卡付成功页领取讲义 questionAfterSalesBtn
  advTagCommonPopPreSales = 'commonPopPreSales';//通用支付提示弹窗—联系客服 commonPopPreSales
  advTagMineContactUs = 'mineContactUs';//个人中心页—通用联系客服 mineContactUs
  advTagDiscussQuestion = 'discussQuestion';//题目详情页—找辅导员讨论 discussQuestion
  advTagAnswerQuestion = 'answerQuestion';//备考答疑页—找老师答疑 answerQuestion
  advTagConsultteachers = 'consultteachers';///自考专业选择-找老师答疑 consultteachers
  hotMajorBanner = 'hotMajorBanner';///高职单招首页专业测评hotMajorBanner
  majorTestBanner = 'majorTestBanner';//高职单招志愿页面专业测评入口majorTestBanner
  majorTestReportText = 'majorTestReportText';//高职单招志愿页面专业测评入口文字广告majorTestBanner
  advOpenPackage = 'openPackage';//统招专升本VIP显示广告
  practiceMidBanner = 'practiceMidBanner';//v1.6.0-首页训练营和模考大赛
  videoDetailsPageAD = 'videoDetailsPageAD';//辅警协警课程详情企微
  findBanner = 'FindBanner';///弹窗
  wecomUnlockTk = 'wecomUnlockTk';///广告添加企微
  courseListBanner = 'courseListBanner';///全部课程广告位
  courseDetailBanner = 'courseDetailBanner';///课程详情广告位
  yCCourseBanner = 'YCCourseBanner';///演出经纪人课程页胶囊广告位
  goodsPayAD = 'GoodsPayAD';///演出经纪人购买页悬浮广告位
  advTagAdultKnowBanner = 'knowTopBanner';/// 成考知道页面Banner
  advTagBktckkcTopBanner = 'BktckkcTopBanner';/// 备考通-成考-首页
  advTagBktcktkTopBanner = 'BktcktkTopBanner';/// 备考通-成考-题库
  advTagBktcksyTopBanner = 'BktcksyTopBanner';/// 备考通-成考-课程
  advRecruitkSLMoreAd = 'recruitkSLMoreAd';/// 招警-申论
  advRecruitkGZMoreAd = 'recruitkGZMoreAd';/// 备考通-公招

  baikemidBanner = 'baikemidBanner';/// 单招百科
  inforPackBanner = 'inforPackBanner';/// 单招学习页
  baikeTopBanner = 'baikeTopBanner';/// 百科首页banner
  cetthreeIndexBanner = 'cetthreeIndexBanner'; ///英语三级首页
  dYWrittenCourseBanner = 'DYWrittenCourseBanner';/// 导游笔试课程
  dYCourseDetailsBanner = 'DYCourseDetailsBanner';/// 导游课程详情
  ///
  YCInformationBanner = 'YCInformationBanner';/// 百科首页banner
  advTagAgentLearnBottomBanner = 'YCWelfareBanner';/// 1.6.5演出经纪人学员福利banner
  advTagAgentLoginPageBanner = 'LoginPageBanner';/// 1.6.5演出经纪人登陆页面banner

}

export default  new AdvTagList()